#!/bin/bash

#SBATCH --time=24:00:00
#SBATCH --ntasks=1
#SBATCH --nodes=1
#SBATCH --mem=256000M
#SBATCH --gpus=8
#SBATCH --mail-type=FAIL
#SBATCH --mail-user %u@byu.edu
#SBATCH --output /home/%u/groups/grp_asl_classification/nobackup/archive/SLR/slurm_outputs/%A_%a_%x.out
#SBATCH --job-name=enc_test
#SBATCH --qos=matrix

# Array job for running TEST evaluation on trained encoder comparison models.
# Each array task occupies one full node (8 GPUs) and runs up to 8 tests in
# parallel — one per GPU — using CUDA_VISIBLE_DEVICES. This keeps all GPUs
# busy rather than leaving 7 idle per test.
#
# Config list: tab-separated file with one "config  jobname" entry per line.
# Each array task handles a chunk of GPUS_PER_NODE consecutive entries.
#
# Usage (generated by scripts/submit_encoder_tests.sh — do not call directly):
#   sbatch --array=0-N%THROTTLE sbatch/test_encoder_array.sh <test_config_list>

GPUS_PER_NODE=8
CONFIG_LIST=${1:?"Error: test config list required"}

if [ ! -f "$CONFIG_LIST" ]; then
    echo "Error: Config list not found: $CONFIG_LIST"
    exit 1
fi

export TRANSFORMERS_OFFLINE=1
export HF_DATASETS_OFFLINE=1
export HF_HUB_OFFLINE=1

source ~/.bashrc
conda init
conda activate asl

echo "=========================================="
echo "Encoder Test Array Task"
echo "Array ID: ${SLURM_ARRAY_JOB_ID}, Task: ${SLURM_ARRAY_TASK_ID}"
echo "Node: $SLURMD_NODENAME"
echo "Start: $(date)"
echo "=========================================="

nvidia-smi --query-gpu=index,name --format=csv,noheader

# Calculate which configs this task is responsible for
START=$(( SLURM_ARRAY_TASK_ID * GPUS_PER_NODE ))
PIDS=()

for gpu_id in $(seq 0 $(( GPUS_PER_NODE - 1 ))); do
    line_num=$(( START + gpu_id + 1 ))
    LINE=$(sed -n "${line_num}p" "$CONFIG_LIST")
    CONFIG=$(echo "$LINE" | awk '{print $1}')
    JOBNAME=$(echo "$LINE" | awk '{print $2}')

    # No more configs — this GPU slot is empty
    [ -z "$CONFIG" ] && break

    # Derive save dir from config path and temporarily MOVE last.ckpt out of
    # the checkpoints/ dir so train.py's checkpoint discovery doesn't try to
    # parse it (it iterates all files and crashes on any name without
    # "-val_acc=" in it — including "last.ckpt.bak"). Moved back after the
    # test completes.
    rel=${CONFIG#configs/encoder_comparison/}
    subdir="${rel%.yaml}"
    save_dir="/home/$USER/groups/grp_asl_classification/nobackup/archive/SLR/models/encoder_comparison/$subdir"
    last_ckpt="$save_dir/checkpoints/last.ckpt"
    last_hidden="$save_dir/last.ckpt.bak"
    [ -f "$last_ckpt" ] && mv "$last_ckpt" "$last_hidden"

    echo "------------------------------------------"
    echo "GPU $gpu_id → $JOBNAME"
    echo "  Config: $CONFIG"
    echo "  Save:   $save_dir"

    SLURM_OUT="/home/$USER/groups/grp_asl_classification/nobackup/archive/SLR/slurm_outputs"
    CUDA_VISIBLE_DEVICES=$gpu_id python src/train.py -c "$CONFIG" -m TEST \
        > "$SLURM_OUT/${SLURM_ARRAY_JOB_ID}_${SLURM_ARRAY_TASK_ID}_gpu${gpu_id}_${JOBNAME}.testlog" 2>&1 &
    PIDS+=($!)
done

echo "=========================================="
echo "Launched ${#PIDS[@]} test processes — waiting for completion..."

# Wait for all background tests, collect exit codes, restore last.ckpt backups
FAILED=0
for i in "${!PIDS[@]}"; do
    pid=${PIDS[$i]}
    wait "$pid"
    code=$?
    line_num=$(( START + i + 1 ))
    LINE=$(sed -n "${line_num}p" "$CONFIG_LIST")
    JOBNAME=$(echo "$LINE" | awk '{print $2}')
    CONFIG_I=$(echo "$LINE" | awk '{print $1}')

    # Restore last.ckpt from its out-of-dir hiding spot
    rel_i=${CONFIG_I#configs/encoder_comparison/}
    subdir_i="${rel_i%.yaml}"
    save_dir_i="/home/$USER/groups/grp_asl_classification/nobackup/archive/SLR/models/encoder_comparison/$subdir_i"
    bak="${save_dir_i}/last.ckpt.bak"
    [ -f "$bak" ] && mv "$bak" "${save_dir_i}/checkpoints/last.ckpt"

    if [ $code -ne 0 ]; then
        echo "FAILED (exit $code): $JOBNAME"
        FAILED=$(( FAILED + 1 ))
    else
        echo "OK: $JOBNAME"
    fi
done

echo "=========================================="
echo "End time: $(date)"
echo "Tasks completed: $(( ${#PIDS[@]} - FAILED )) / ${#PIDS[@]}"
[ $FAILED -gt 0 ] && echo "FAILURES: $FAILED" && exit 1
echo "=========================================="