#!/bin/bash
# Downloads and extracts the ASL Citizen dataset into the archive directory.
#
# Usage: run this script from inside the target data directory, e.g.:
#   cd /home/$USER/groups/grp_asl_classification/nobackup/archive/ASL
#   sh /path/to/download_asl_citizen.sh
#
# Expected structure after running:
#   ASL/
#   ├── ASL_Citizen.zip
#   ├── ASL_Citizen/
#   │   └── splits/
#   │       ├── train.csv    <- Participant ID, Video file, Gloss, ASL-LEX Code
#   │       ├── val.csv
#   │       └── test.csv
#   ├── videos/              <- all ~84k MP4 files (flat)
#   └── skel/                <- skeleton .npy files (generated by pose_points.py)
#
# After this script, run:
#   sbatch sbatch/extract_pose_points.asl_citizen.sh   <- generates skel/
#   sh sh/make_asl_citizen_data_sets.sh                <- generates pipeline CSVs

set -e

echo "Downloading ASL Citizen zip (~45 GB)..."
wget -c https://download.microsoft.com/download/b/8/8/b88c0bae-e6c1-43e1-8726-98cf5af36ca4/ASL_Citizen.zip

echo "Unzipping..."
unzip -o ASL_Citizen.zip

# The zip extracts to ASL_Citizen/ with splits/ subdir and a videos/ dir at root.
# Move videos to the top-level if the zip put them inside ASL_Citizen/.
if [ -d "ASL_Citizen/videos" ] && [ ! -d "videos" ]; then
    echo "Moving videos/ to top-level..."
    mv ASL_Citizen/videos .
fi

# Create the skeleton output directory for pose_points.py
mkdir -p skel

echo ""
echo "Done. Directory contents:"
ls -lh
echo ""
echo "CSV files found:"
ls *.csv 2>/dev/null || echo "  WARNING: no .csv files found - check zip structure"
echo ""
echo "Video count:"
ls videos/*.mp4 2>/dev/null | wc -l || echo "  WARNING: no videos found - check zip structure"
echo ""
echo "Next steps:"
echo "  1. sbatch sbatch/extract_pose_points.asl_citizen.sh"
echo "  2. sh sh/make_asl_citizen_data_sets.sh"
